<template src='./template.html'>
  
</template>

<script>
export default {
  data(){
    return{
      active:false,
      activeindex:-1,
      activeindex_content:-1,
      activelist:-1,
      input_active:false,
      sub_content:false,
      sub_sub_content:false,
      hove_1:false,
      hove_2:false,
      hove_3:false,
      hove_4:false,
      hove_5:false,
      mb_menu:{
          mb_active:false,
          mb:false,
      }
    }
  },

  created(){
    window.addEventListener("scroll",this.handleScroll)
    this.judgPc()
  },
  props:[
      'activeLogin'
  ],
  computed:{
      main_data(){
          return [
              {
                  title:'自行車系列',
                  list:[
                      {
                          title:'踏板',
                          content:[
                              '公路踏板',
                              '室內踏板',
                              '戶外踏板',
                              '山地車踏板',
                              'BMX踏板',
                              '追蹤踏板',
                              '城市踏板',
                              '速配器',
                          ]
                      },
                      {
                          title:'防滑釘',
                          content:[
                              'ERS-R',
                              'ERS',
                              'ERS-R(Wide Beam)',
                              'ERS-SL',
                              'ERS-M',
                              'ERS-T',
                              '防滑墊套',
                          ]
                      },
                      {
                          title:'鞋',
                          content:[
                              '公路鞋',
                              '室內鞋',
                              '山地車鞋',
                              '小輪車鞋',
                              '鐵人三項鞋',
                              '涼鞋',
                              '冬季鞋',
                          ]
                      },
                      {
                          title:'服裝',
                          content:[
                              '球衣',
                              '運動衫',
                              '短褲/褲襪',
                              '外套',
                              '手套',
                              '襪子',
                              '手套/腿套',
                              '頭飾',
                              '鞋套',
                              '女性服飾',
                              '兒童服飾',
                          ]
                      },
                      {
                          title:'配件',
                          content:[
                              '訂製踏板人體工程學',
                              '頭盔',
                              '眼鏡',
                              '水壺和籠子',
                              '攜泥板',
                              '鏈條指南',
                              '包',
                              '自行車保養',
                              '工具集',
                          ]
                      },
                      {
                          title:'零售商產品',
                          content:[
                              '自行車健身機',
                              '腳測量',
                              '展示架',
                          ]
                      },
                      {
                          title:'工具集',
                          content:[
                              '工具集1',
                              '工具集2',
                              '工具集3',
                          ]
                      },
                  ]
              },
              {
                  title:'摩托車系列',
                  list:[
                      {
                          title:'踏板',
                          content:[
                              '公路踏板',
                              '室內踏板',
                              '戶外踏板',
                              '山地車踏板',
                              'BMX踏板',
                              '追蹤踏板',
                              '城市踏板',
                              '速配器',
                          ]
                      },
                      {
                          title:'防滑釘',
                          content:[
                              'ERS-R',
                              'ERS',
                              'ERS-R(Wide Beam)',
                              'ERS-SL',
                              'ERS-M',
                              'ERS-T',
                              '防滑墊套',
                          ]
                      },
                      {
                          title:'鞋',
                          content:[
                              '公路鞋',
                              '室內鞋',
                              '山地車鞋',
                              '小輪車鞋',
                              '鐵人三項鞋',
                              '涼鞋',
                              '冬季鞋',
                          ]
                      },
                      {
                          title:'服裝',
                          content:[
                              '球衣',
                              '運動衫',
                              '短褲/褲襪',
                              '外套',
                              '手套',
                              '襪子',
                              '手套/腿套',
                              '頭飾',
                              '鞋套',
                              '女性服飾',
                              '兒童服飾',
                          ]
                      },
                      {
                          title:'配件',
                          content:[
                              '訂製踏板人體工程學',
                              '頭盔',
                              '眼鏡',
                              '水壺和籠子',
                              '攜泥板',
                              '鏈條指南',
                              '包',
                              '自行車保養',
                              '工具集',
                          ]
                      },
                      {
                          title:'零售商產品',
                          content:[
                              '自行車健身機',
                              '腳測量',
                              '展示架',
                          ]
                      },
                      {
                          title:'工具集',
                          content:[
                              '工具集1',
                              '工具集2',
                              '工具集3',
                          ]
                      },
                  ]
              },
              {
                  title:'室內健身',
                  list:[
                      {
                          title:'踏板',
                          content:[
                              '公路踏板',
                              '室內踏板',
                              '戶外踏板',
                              '山地車踏板',
                              'BMX踏板',
                              '追蹤踏板',
                              '城市踏板',
                              '速配器',
                          ]
                      },
                      {
                          title:'防滑釘',
                          content:[
                              'ERS-R',
                              'ERS',
                              'ERS-R(Wide Beam)',
                              'ERS-SL',
                              'ERS-M',
                              'ERS-T',
                              '防滑墊套',
                          ]
                      },
                      {
                          title:'鞋',
                          content:[
                              '公路鞋',
                              '室內鞋',
                              '山地車鞋',
                              '小輪車鞋',
                              '鐵人三項鞋',
                              '涼鞋',
                              '冬季鞋',
                          ]
                      },
                      {
                          title:'服裝',
                          content:[
                              '球衣',
                              '運動衫',
                              '短褲/褲襪',
                              '外套',
                              '手套',
                              '襪子',
                              '手套/腿套',
                              '頭飾',
                              '鞋套',
                              '女性服飾',
                              '兒童服飾',
                          ]
                      },
                      {
                          title:'配件',
                          content:[
                              '訂製踏板人體工程學',
                              '頭盔',
                              '眼鏡',
                              '水壺和籠子',
                              '攜泥板',
                              '鏈條指南',
                              '包',
                              '自行車保養',
                              '工具集',
                          ]
                      },
                      {
                          title:'零售商產品',
                          content:[
                              '自行車健身機',
                              '腳測量',
                              '展示架',
                          ]
                      },
                      {
                          title:'工具集',
                          content:[
                              '工具集1',
                              '工具集2',
                              '工具集3',
                          ]
                      },
                  ]
              },
              {
                  title:'活動商品',
                  list:[
                      {
                          title:'踏板',
                          content:[
                              '公路踏板',
                              '室內踏板',
                              '戶外踏板',
                              '山地車踏板',
                              'BMX踏板',
                              '追蹤踏板',
                              '城市踏板',
                              '速配器',
                          ]
                      },
                      {
                          title:'防滑釘',
                          content:[
                              'ERS-R',
                              'ERS',
                              'ERS-R(Wide Beam)',
                              'ERS-SL',
                              'ERS-M',
                              'ERS-T',
                              '防滑墊套',
                          ]
                      },
                      {
                          title:'鞋',
                          content:[
                              '公路鞋',
                              '室內鞋',
                              '山地車鞋',
                              '小輪車鞋',
                              '鐵人三項鞋',
                              '涼鞋',
                              '冬季鞋',
                          ]
                      },
                      {
                          title:'服裝',
                          content:[
                              '球衣',
                              '運動衫',
                              '短褲/褲襪',
                              '外套',
                              '手套',
                              '襪子',
                              '手套/腿套',
                              '頭飾',
                              '鞋套',
                              '女性服飾',
                              '兒童服飾',
                          ]
                      },
                      {
                          title:'配件',
                          content:[
                              '訂製踏板人體工程學',
                              '頭盔',
                              '眼鏡',
                              '水壺和籠子',
                              '攜泥板',
                              '鏈條指南',
                              '包',
                              '自行車保養',
                              '工具集',
                          ]
                      },
                      {
                          title:'零售商產品',
                          content:[
                              '自行車健身機',
                              '腳測量',
                              '展示架',
                          ]
                      },
                      {
                          title:'工具集',
                          content:[
                              '工具集1',
                              '工具集2',
                              '工具集3',
                          ]
                      },
                  ]
              },
              {
                  title:'OUTLET',
                  list:[
                      {
                          title:'踏板',
                          content:[
                              '公路踏板',
                              '室內踏板',
                              '戶外踏板',
                              '山地車踏板',
                              'BMX踏板',
                              '追蹤踏板',
                              '城市踏板',
                              '速配器',
                          ]
                      },
                      {
                          title:'防滑釘',
                          content:[
                              'ERS-R',
                              'ERS',
                              'ERS-R(Wide Beam)',
                              'ERS-SL',
                              'ERS-M',
                              'ERS-T',
                              '防滑墊套',
                          ]
                      },
                      {
                          title:'鞋',
                          content:[
                              '公路鞋',
                              '室內鞋',
                              '山地車鞋',
                              '小輪車鞋',
                              '鐵人三項鞋',
                              '涼鞋',
                              '冬季鞋',
                          ]
                      },
                      {
                          title:'服裝',
                          content:[
                              '球衣',
                              '運動衫',
                              '短褲/褲襪',
                              '外套',
                              '手套',
                              '襪子',
                              '手套/腿套',
                              '頭飾',
                              '鞋套',
                              '女性服飾',
                              '兒童服飾',
                          ]
                      },
                      {
                          title:'配件',
                          content:[
                              '訂製踏板人體工程學',
                              '頭盔',
                              '眼鏡',
                              '水壺和籠子',
                              '攜泥板',
                              '鏈條指南',
                              '包',
                              '自行車保養',
                              '工具集',
                          ]
                      },
                      {
                          title:'零售商產品',
                          content:[
                              '自行車健身機',
                              '腳測量',
                              '展示架',
                          ]
                      },
                      {
                          title:'工具集',
                          content:[
                              '工具集1',
                              '工具集2',
                              '工具集3',
                          ]
                      },
                  ]
              },
          ]
      }
  },
  methods:{
    handleScroll() {
      var scrollTop =
        window.pageYOffset ||
        document.documentElement.scrollTop ||
        document.body.scrollTop;
        var width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
      if (scrollTop > 45 && width>992) {
        this.active = true
      } else {
        this.active = false
      }
    },
    judgPc(){
        var width = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
        if(width <= 992){
            console.log('124514')
            this.mb_menu.mb = true
        }
    },
    inputOpen(){
        this.input_active =! this.input_active
    },
    changActive(toIndex){
        this.activeindex = toIndex
    },
    leaveActive(){
        console.log(123)
        this.activeindex = -1
    },

    //mobile  //.

    mbMenuActive(){   
        this.mb_menu.mb_active = true
        document.querySelector('body').setAttribute('style', 'overflow:hidden')
    },
    mbCloseMenuActive(){   
        this.mb_menu.mb_active = false
        document.querySelector('body').setAttribute('style', 'overflow:visible')
    },
    subContentMove(){
            this.sub_content = true
    },
    closeSubContentMove(){
            this.sub_content = false
    },
    mobileChangActive(toIndex){
        console.log(toIndex)
        this.activeindex = toIndex
    },
    changList(toIndex){
        console.log(toIndex)
        this.activelist = toIndex
        this.sub_sub_content = true
    },
    closeSubSubContent(){
        this.sub_sub_content = false
    }
  }
}
</script>

<style>

</style>